name: po-community-mcp

services:
  typescript:
    restart: always
    build:
      context: ./typescript
      dockerfile: Dockerfile
    ports:
      - "55000:5000"
    environment:
      - PO_ENV=local
      - LOG_LEVEL=debug
